sudo: required

language: go
go_import_path: github.com/ExpdiaDotCom/haystack-istio



matrix:
  include:
  - go: 1.9

services:
  - docker

script:
  - make setup
  - pwd
  - ls -l
  - make -C ../../../istio.io/istio/mixer/adapter/haystack validate build
