sudo: required

language: go
go_import_path: github.com/ExpdiaDotCom/haystack-istio

dist: trusty

matrix:
  include:
  - go: 1.9

services:
  - docker

env:
  global:
    - IS_TRAVIS=true
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}

addons:
  hosts:
    - mixs
    - kafkasvc

script:
  - make setup
  - make -C $GOPATH/src/istio.io/istio/mixer/adapter/haystack validate integration_tests
  - if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ -n "$TRAVIS_TAG" ];  then make -C $GOPATH/src/istio.io/istio/mixer/adapter/haystack publish; fi

notifications:
  email:
    - haystack-notifications@expedia.com