sudo: required

language: go
go_import_path: github.com/ExpdiaDotCom/haystack-istio

dist: trusty

matrix:
  include:
  - go: 1.9

services:
  - docker

script:
  - make setup
  - make -C $GOPATH/src/istio.io/istio/mixer/adapter/haystack validate build