apiVersion: v1
kind: Service
metadata:
  name: haystack-adapter
  namespace: istio-system
  labels:
    app: haystack-adapter
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: haystack-adapter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: istio-system
  name: haystack-adapter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: haystack-adapter
        version: v1
    spec:
      containers:
      - image: ExpediaDotCom/haystack-agent:latest
        name: haystack-agent
        ports:
        - containerPort: 35000
      - image:  ExpediaDotCom/haystack-istio-adapter:latest
        name: haystack-adapter
        args:
          - "-port"
          - "8080"
        ports:
        - containerPort: 8080
